sudo: false
language: java

addons:
  apt:
    packages:
      - oracle-java8-installer
      
cache:
  directories:
  - "$HOME/.cache"
  - "$HOME/.m2"

after_success:
  - mvn clean cobertura:cobertura coveralls:report
  - bash <(curl -s https://codecov.io/bash) 
